### ISSUE TITLE
Create walkthrough

### ISSUE THREAD

**Issue by koppor** [JabRef/user-documentation#266] opened 2020-03-28 12:03 UTC
Idea: step-by-step usage of JabRef. Modernize "A guide to using JabRef" - https://www.mcgill.ca/library/files/library/jabref_guide_2016.pdf

**Comment by tobiasdiez** [comment] 2020-05-22 12:54
Just discovered that this is essentially a duplicate of #278

**Closed by tobiasdiez** 2020-05-22 12:54 UTC
Labels: enhancement
