### ISSUE TITLE
ElephantSQL is dicontinued

### ISSUE THREAD

**Issue by InAnYan** [JabRef/user-documentation#522] opened 2024-10-06 10:23 UTC
The link on ElephantSQL is here: https://docs.jabref.org/collaborative-work/sqldatabase

https://www.elephantsql.com/blog/end-of-life-announcement.html

**Comment by Siedlerchr** [comment] 2024-10-06 12:33
There's an issue in the melting pot with alternatives

Ruslan ***@***.***> schrieb am So., 6. Okt. 2024, 12:23:

**Comment by Siedlerchr** [comment] 2024-10-09 12:59
Duplicate of https://github.com/JabRef/user-documentation/issues/494

**Closed by Siedlerchr** 2024-10-09 12:59 UTC
